using System.Text.Json;
using Microsoft.Data.Sqlite;
using MRVA.Reports.Data.Models;

namespace MRVA.Reports.Data.Services;

public sealed class DataStore : IDisposable
{
    private SqliteConnection? _connection;

    private const string DbPath = "/mrva.db";

    // ── Database readiness (background loading) ──────────────────────────
    private readonly TaskCompletionSource _databaseReady = new();

    /// <summary>
    /// Returns a task that completes when the SQLite database has been
    /// fully loaded and is ready for queries. Drill-down pages should
    /// await this before accessing the database.
    /// </summary>
    public Task WaitForDatabaseAsync() => _databaseReady.Task;

    // ── Caches (DB is read-only, so results never change) ───────────────
    private DashboardStats? _cachedDashboardStats;
    private List<RepositoryDetail>? _cachedAllRepoDetails;
    private List<RuleDetail>? _cachedAllRuleDetails;
    private readonly Dictionary<(int Page, int PageSize, string? Search), (List<AlertHeaderDetail> Items, int TotalCount)> _alertHeaderPageCache = [];

    // ── JSON serialization options (match mrva-prep camelCase output) ────
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    /// <summary>
    /// Loads dashboard statistics from a pre-built JSON file generated by
    /// mrva-prep. This enables instant first-paint of the dashboard while
    /// the full SQLite database downloads in the background.
    /// </summary>
    public void LoadDashboardFromJson(string json)
    {
        _cachedDashboardStats = JsonSerializer.Deserialize<DashboardStats>(json, JsonOptions)
            ?? throw new InvalidOperationException("Failed to deserialize dashboard.json");
    }

    /// <summary>
    /// Writes the decompressed SQLite database bytes to Emscripten MEMFS
    /// and opens the connection. Decompression should be performed by the
    /// browser's native <c>DecompressionStream</c> API before calling this
    /// method. Indexes must be pre-built in the DB at generation time.
    /// Signals <see cref="WaitForDatabaseAsync"/> upon completion.
    /// </summary>
    public Task InitializeAsync(byte[] dbBytes)
    {
        File.WriteAllBytes(DbPath, dbBytes);

        _connection = new SqliteConnection($"Data Source={DbPath}");
        _connection.Open();

        // Tune for a read-only, in-memory (MEMFS) database.
        // Note: Mode=ReadOnly and query_only are omitted because
        // GetDashboardStats() uses a TEMP TABLE which requires write access.
        using var pragma = _connection.CreateCommand();
        pragma.CommandText = """
            PRAGMA journal_mode = OFF;
            PRAGMA synchronous = OFF;
            PRAGMA locking_mode = EXCLUSIVE;
            PRAGMA temp_store = MEMORY;
            PRAGMA cache_size = -64000;
            """;
        pragma.ExecuteNonQuery();

        _databaseReady.TrySetResult();

        return Task.CompletedTask;
    }

    private SqliteConnection Connection =>
        _connection ?? throw new InvalidOperationException("DataStore has not been initialized. Call Initialize first.");

    // ── Dashboard (single-pass) ───────────────────────────────────────────

    public DashboardStats GetDashboardStats()
    {
        if (_cachedDashboardStats is not null)
            return _cachedDashboardStats;

        // Materialize the expensive three-table join once into a temp table,
        // then run lightweight aggregations against it.
        using var createCmd = Connection.CreateCommand();
        createCmd.CommandText = """
            DROP TABLE IF EXISTS _dash;
            CREATE TEMP TABLE _dash AS
            SELECT a.file_path, a.repository_row_id, a.rule_row_id,
                   r.id AS rule_id, COALESCE(r.severity_level, 'unknown') AS severity,
                   repo.repository_full_name
            FROM alert a
            JOIN rule r ON a.rule_row_id = r.row_id
            JOIN repository repo ON a.repository_row_id = repo.row_id;
            """;
        createCmd.ExecuteNonQuery();

        try
        {
            using var cmd = Connection.CreateCommand();
            cmd.CommandText = """
                SELECT
                    (SELECT COUNT(*) FROM _dash)                          AS alert_count,
                    (SELECT COUNT(*) FROM repository)                     AS repo_count,
                    (SELECT COUNT(*) FROM rule)                           AS rule_count,
                    (SELECT COUNT(DISTINCT repository_row_id) FROM _dash) AS repos_with_alerts,
                    (SELECT COUNT(DISTINCT rule_row_id)       FROM _dash) AS rules_with_alerts;

                SELECT severity, COUNT(*) AS cnt
                FROM _dash
                GROUP BY severity
                ORDER BY cnt DESC;

                SELECT rule_id, COUNT(*) AS cnt
                FROM _dash
                GROUP BY rule_id
                ORDER BY cnt DESC
                LIMIT 10;

                SELECT repository_full_name, COUNT(*) AS cnt
                FROM _dash
                GROUP BY repository_row_id
                ORDER BY cnt DESC
                LIMIT 10;

                SELECT file_path, repository_full_name, COUNT(*) AS cnt
                FROM _dash
                WHERE file_path IS NOT NULL AND file_path != ''
                GROUP BY file_path, repository_row_id
                ORDER BY cnt DESC
                LIMIT 10;
                """;

            using var reader = cmd.ExecuteReader();

            // Result set 1: scalar counts
            reader.Read();
            var alertCount = reader.GetInt32(0);
            var repoCount = reader.GetInt32(1);
            var ruleCount = reader.GetInt32(2);
            var reposWithAlerts = reader.GetInt32(3);
            var rulesWithAlerts = reader.GetInt32(4);

            // Result set 2: severity breakdown
            reader.NextResult();
            var severityCounts = new List<SeverityCount>();
            while (reader.Read())
            {
                var label = reader.GetString(0);
                severityCounts.Add(new SeverityCount(
                    string.IsNullOrEmpty(label) ? "unknown" : label,
                    reader.GetInt32(1)));
            }

            // Result set 3: top rules
            reader.NextResult();
            var topRules = new List<RuleAlertSummary>();
            while (reader.Read())
            {
                topRules.Add(new RuleAlertSummary(reader.GetString(0), reader.GetInt32(1)));
            }

            // Result set 4: top repos
            reader.NextResult();
            var topRepos = new List<RepositoryAlertSummary>();
            while (reader.Read())
            {
                topRepos.Add(new RepositoryAlertSummary(reader.GetString(0), reader.GetInt32(1)));
            }

            // Result set 5: top file paths
            reader.NextResult();
            var topFiles = new List<FilePathAlertSummary>();
            while (reader.Read())
            {
                topFiles.Add(new FilePathAlertSummary(reader.GetString(0), reader.GetString(1), reader.GetInt32(2)));
            }

            var analysis = GetFirstAnalysis();

            _cachedDashboardStats = new DashboardStats(
                AlertCount: alertCount,
                RepositoryCount: repoCount,
                RuleCount: ruleCount,
                ReposWithAlerts: reposWithAlerts,
                RulesWithAlerts: rulesWithAlerts,
                Analysis: analysis,
                SeverityCounts: severityCounts,
                TopRules: topRules,
                TopRepositories: topRepos,
                TopFilePaths: topFiles);

            return _cachedDashboardStats;
        }
        finally
        {
            using var dropCmd = Connection.CreateCommand();
            dropCmd.CommandText = "DROP TABLE IF EXISTS _dash";
            dropCmd.ExecuteNonQuery();
        }
    }

    // ── Analysis ────────────────────────────────────────────────────────

    public Analysis? GetFirstAnalysis()
    {
        using var cmd = Connection.CreateCommand();
        cmd.CommandText = "SELECT * FROM analysis LIMIT 1";
        using var reader = cmd.ExecuteReader();

        if (!reader.Read())
        {
            return null;
        }

        return ReadAnalysis(reader);
    }

    // ── Alert Headers (lightweight, for grid listing) ────────────────────

    /// <summary>
    /// Returns a page of alert headers (no snippets, message, or fingerprint)
    /// together with the total count. This is significantly lighter than
    /// <see cref="GetAlertDetailsPaged"/> because it skips large text columns.
    /// </summary>
    public (List<AlertHeaderDetail> Items, int TotalCount) GetAlertHeadersPaged(int page, int pageSize, string? search)
    {
        var cacheKey = (page, pageSize, search);
        if (_alertHeaderPageCache.TryGetValue(cacheKey, out var cached))
            return cached;

        using var cmd = Connection.CreateCommand();
        var (whereClause, parameters) = BuildAlertSearchClause(search);
        cmd.CommandText = $"""
            SELECT
                a.row_id,
                a.file_path,
                r.id AS rule_name, r.kind AS rule_kind, COALESCE(r.severity_level, 'unknown') AS severity,
                repo.repository_full_name AS repo_name,
                COUNT(*) OVER() AS total_count
            FROM alert a
            JOIN rule r ON a.rule_row_id = r.row_id
            JOIN repository repo ON a.repository_row_id = repo.row_id
            {whereClause}
            ORDER BY a.row_id
            LIMIT @limit OFFSET @offset
            """;
        cmd.Parameters.AddWithValue("@limit", pageSize);
        cmd.Parameters.AddWithValue("@offset", page * pageSize);
        foreach (var (name, value) in parameters)
        {
            cmd.Parameters.AddWithValue(name, value);
        }

        var results = new List<AlertHeaderDetail>();
        var totalCount = 0;
        using var reader = cmd.ExecuteReader();
        while (reader.Read())
        {
            if (totalCount == 0)
                totalCount = reader.GetInt32(reader.GetOrdinal("total_count"));

            results.Add(new AlertHeaderDetail(
                AlertRowId: reader.GetInt32(reader.GetOrdinal("row_id")),
                FilePath: reader.GetString(reader.GetOrdinal("file_path")),
                RuleName: reader.GetString(reader.GetOrdinal("rule_name")),
                RuleKind: reader.GetString(reader.GetOrdinal("rule_kind")),
                RepositoryName: reader.GetString(reader.GetOrdinal("repo_name")),
                Severity: reader.GetString(reader.GetOrdinal("severity"))));
        }

        var result = (results, totalCount);
        _alertHeaderPageCache[cacheKey] = result;
        return result;
    }

    // ── Single Alert (full detail, fetched on demand) ───────────────────

    /// <summary>
    /// Returns the full alert record for a given row ID, including all
    /// code snippet and message columns. Used for on-demand detail loading.
    /// </summary>
    public AlertDetail? GetAlertDetailByRowId(int rowId)
    {
        using var cmd = Connection.CreateCommand();
        cmd.CommandText = """
            SELECT
                a.row_id, a.file_path, a.start_line, a.start_column, a.end_line, a.end_column,
                a.code_snippet_source, a.code_snippet_sink, a.code_snippet, a.code_snippet_context,
                a.message, a.result_fingerprint, a.step_count,
                a.repository_row_id, a.rule_row_id,
                r.id AS rule_name, r.kind AS rule_kind, COALESCE(r.severity_level, 'unknown') AS severity,
                repo.repository_full_name AS repo_name
            FROM alert a
            JOIN rule r ON a.rule_row_id = r.row_id
            JOIN repository repo ON a.repository_row_id = repo.row_id
            WHERE a.row_id = @rowId
            """;
        cmd.Parameters.AddWithValue("@rowId", rowId);

        using var reader = cmd.ExecuteReader();
        if (!reader.Read())
            return null;

        var alert = ReadAlert(reader);
        return new AlertDetail(
            alert,
            reader.GetString(reader.GetOrdinal("rule_name")),
            reader.GetString(reader.GetOrdinal("rule_kind")),
            reader.GetString(reader.GetOrdinal("repo_name")),
            reader.GetString(reader.GetOrdinal("severity")));
    }

    private static (string WhereClause, List<(string Name, string Value)> Parameters) BuildAlertSearchClause(string? search)
    {
        if (string.IsNullOrWhiteSpace(search))
        {
            return ("", []);
        }

        // Search only the most useful columns. The snippet and fingerprint
        // columns are large text blobs that are expensive to scan with
        // leading-wildcard LIKE and rarely match user intent. For full-text
        // search across all content, consider adding an FTS5 virtual table
        // at DB generation time.
        var clause = """
            WHERE (
                r.id LIKE @search ESCAPE '\'
                OR r.kind LIKE @search ESCAPE '\'
                OR repo.repository_full_name LIKE @search ESCAPE '\'
                OR COALESCE(r.severity_level, '') LIKE @search ESCAPE '\'
                OR a.file_path LIKE @search ESCAPE '\'
                OR a.message LIKE @search ESCAPE '\'
            )
            """;

        // Escape LIKE wildcards so literal %, _, and \ in the user's
        // search term are matched exactly rather than treated as patterns.
        var escaped = search
            .Replace(@"\", @"\\")
            .Replace("%", @"\%")
            .Replace("_", @"\_");

        return (clause, [("@search", $"%{escaped}%")]);
    }

    // ── Repository Details (with alert counts) ──────────────────────────

    public List<RepositoryDetail> GetRepositoryDetails(
        string? hasAlertsFilter,
        string? statusFilter)
    {
        // Pre-compute all repo details once (with a lightweight subquery
        // instead of LEFT JOIN on the full alert table), then filter in memory.
        if (_cachedAllRepoDetails is null)
        {
            using var cmd = Connection.CreateCommand();
            cmd.CommandText = """
                SELECT
                    r.row_id, r.repository_full_name, r.repository_url, r.analysis_status,
                    r.result_count, r.artifact_size_in_bytes, r.analysis_id,
                    COALESCE(ac.cnt, 0) AS alert_count
                FROM repository r
                LEFT JOIN (
                    SELECT repository_row_id, COUNT(*) AS cnt
                    FROM alert
                    GROUP BY repository_row_id
                ) ac ON r.row_id = ac.repository_row_id
                ORDER BY r.repository_full_name
                """;

            _cachedAllRepoDetails = [];
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                var repo = ReadRepository(reader);
                _cachedAllRepoDetails.Add(new RepositoryDetail(repo, reader.GetInt32(reader.GetOrdinal("alert_count"))));
            }
        }

        IEnumerable<RepositoryDetail> filtered = _cachedAllRepoDetails;

        if (hasAlertsFilter == "true")
            filtered = filtered.Where(r => r.AlertCount > 0);
        else if (hasAlertsFilter == "false")
            filtered = filtered.Where(r => r.AlertCount == 0);

        if (!string.IsNullOrEmpty(statusFilter))
            filtered = filtered.Where(r => r.Repository.AnalysisStatus == statusFilter);

        return filtered.ToList();
    }

    // ── Rule Details (with alert counts) ────────────────────────────────

    public List<RuleDetail> GetRuleDetails(string? hasAlertsFilter)
    {
        // Pre-compute all rule details once (with a lightweight subquery
        // instead of LEFT JOIN on the full alert table), then filter in memory.
        if (_cachedAllRuleDetails is null)
        {
            using var cmd = Connection.CreateCommand();
            cmd.CommandText = """
                SELECT
                    r.row_id, r.id, r.rule_name, r.rule_description, r.property_tags,
                    r.kind, r.severity_level,
                    COALESCE(ac.cnt, 0) AS alert_count
                FROM rule r
                LEFT JOIN (
                    SELECT rule_row_id, COUNT(*) AS cnt
                    FROM alert
                    GROUP BY rule_row_id
                ) ac ON r.row_id = ac.rule_row_id
                ORDER BY r.id
                """;

            _cachedAllRuleDetails = [];
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                var rule = ReadRule(reader);
                _cachedAllRuleDetails.Add(new RuleDetail(rule, reader.GetInt32(reader.GetOrdinal("alert_count"))));
            }
        }

        IEnumerable<RuleDetail> filtered = _cachedAllRuleDetails;

        if (hasAlertsFilter == "true")
            filtered = filtered.Where(r => r.AlertCount > 0);
        else if (hasAlertsFilter == "false")
            filtered = filtered.Where(r => r.AlertCount == 0);

        return filtered.ToList();
    }

    // ── Row Mappers ─────────────────────────────────────────────────────

    private static Analysis ReadAnalysis(SqliteDataReader reader) => new()
    {
        RowId = reader.GetInt32(reader.GetOrdinal("row_id")),
        ToolName = reader.GetString(reader.GetOrdinal("tool_name")),
        ToolVersion = GetStringOrEmpty(reader, "tool_version"),
        AnalysisId = reader.GetString(reader.GetOrdinal("analysis_id")),
        ControllerRepo = GetStringOrEmpty(reader, "controller_repo"),
        Date = GetStringOrEmpty(reader, "date"),
        State = reader.GetString(reader.GetOrdinal("state")),
        QueryLanguage = reader.GetString(reader.GetOrdinal("query_language")),
        CreatedAt = reader.GetString(reader.GetOrdinal("created_at")),
        CompletedAt = GetStringOrEmpty(reader, "completed_at"),
        Status = reader.GetString(reader.GetOrdinal("status")),
        FailureReason = GetStringOrEmpty(reader, "failure_reason"),
        ScannedReposCount = reader.GetInt32(reader.GetOrdinal("scanned_repos_count")),
        SkippedReposCount = reader.GetInt32(reader.GetOrdinal("skipped_repos_count")),
        NotFoundReposCount = reader.GetInt32(reader.GetOrdinal("not_found_repos_count")),
        NoCodeqlDbReposCount = reader.GetInt32(reader.GetOrdinal("no_codeql_db_repos_count")),
        OverLimitReposCount = reader.GetInt32(reader.GetOrdinal("over_limit_repos_count")),
        ActionsWorkflowRunId = reader.GetInt64(reader.GetOrdinal("actions_workflow_run_id")),
        TotalReposCount = reader.GetInt32(reader.GetOrdinal("total_repos_count")),
    };

    private static Repository ReadRepository(SqliteDataReader reader) => new()
    {
        RowId = reader.GetInt32(reader.GetOrdinal("row_id")),
        RepositoryFullName = reader.GetString(reader.GetOrdinal("repository_full_name")),
        RepositoryUrl = reader.GetString(reader.GetOrdinal("repository_url")),
        AnalysisStatus = reader.GetString(reader.GetOrdinal("analysis_status")),
        ResultCount = GetIntOrDefault(reader, "result_count"),
        ArtifactSizeInBytes = GetIntOrDefault(reader, "artifact_size_in_bytes"),
        AnalysisId = reader.GetString(reader.GetOrdinal("analysis_id")),
    };

    private static Rule ReadRule(SqliteDataReader reader) => new()
    {
        RowId = reader.GetInt32(reader.GetOrdinal("row_id")),
        Id = reader.GetString(reader.GetOrdinal("id")),
        RuleName = reader.GetString(reader.GetOrdinal("rule_name")),
        RuleDescription = GetStringOrEmpty(reader, "rule_description"),
        PropertyTags = ParseTags(GetStringOrEmpty(reader, "property_tags")),
        Kind = reader.GetString(reader.GetOrdinal("kind")),
        SeverityLevel = GetStringOrEmpty(reader, "severity_level"),
    };

    private static Alert ReadAlert(SqliteDataReader reader) => new()
    {
        RowId = reader.GetInt32(reader.GetOrdinal("row_id")),
        FilePath = reader.GetString(reader.GetOrdinal("file_path")),
        StartLine = GetIntOrDefault(reader, "start_line"),
        StartColumn = GetIntOrDefault(reader, "start_column"),
        EndLine = GetIntOrDefault(reader, "end_line"),
        EndColumn = GetIntOrDefault(reader, "end_column"),
        CodeSnippetSource = GetStringOrEmpty(reader, "code_snippet_source"),
        CodeSnippetSink = GetStringOrEmpty(reader, "code_snippet_sink"),
        CodeSnippet = GetStringOrEmpty(reader, "code_snippet"),
        CodeSnippetContext = GetStringOrEmpty(reader, "code_snippet_context"),
        Message = reader.GetString(reader.GetOrdinal("message")),
        ResultFingerprint = GetStringOrEmpty(reader, "result_fingerprint"),
        StepCount = GetIntOrDefault(reader, "step_count"),
        RepositoryRowId = reader.GetInt32(reader.GetOrdinal("repository_row_id")),
        RuleRowId = reader.GetInt32(reader.GetOrdinal("rule_row_id")),
    };

    // ── Helpers ─────────────────────────────────────────────────────────

    private static string GetStringOrEmpty(SqliteDataReader reader, string column)
    {
        var ordinal = reader.GetOrdinal(column);
        return reader.IsDBNull(ordinal) ? string.Empty : reader.GetString(ordinal);
    }

    private static int GetIntOrDefault(SqliteDataReader reader, string column)
    {
        var ordinal = reader.GetOrdinal(column);
        return reader.IsDBNull(ordinal) ? 0 : reader.GetInt32(ordinal);
    }

    private static IReadOnlyList<string> ParseTags(string tags)
    {
        if (string.IsNullOrWhiteSpace(tags))
        {
            return [];
        }

        return tags.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
    }

    // ── Disposal ────────────────────────────────────────────────────────

    public void Dispose()
    {
        if (_connection is not null)
        {
            _connection.Dispose();
            _connection = null;
        }
    }
}

// ── DTOs for aggregated query results ───────────────────────────────────

public sealed record SeverityCount(string Label, int Count);
public sealed record RuleAlertSummary(string RuleName, int Count);
public sealed record RepositoryAlertSummary(string RepositoryName, int Count);
public sealed record FilePathAlertSummary(string FilePath, string RepositoryName, int Count);
public sealed record AlertHeaderDetail(int AlertRowId, string FilePath, string RuleName, string RuleKind, string RepositoryName, string Severity);
public sealed record AlertDetail(Alert Alert, string RuleName, string RuleKind, string RepositoryName, string Severity);
public sealed record RepositoryDetail(Repository Repository, int AlertCount);
public sealed record RuleDetail(Rule Rule, int AlertCount);

public sealed record DashboardStats(
    int AlertCount,
    int RepositoryCount,
    int RuleCount,
    int ReposWithAlerts,
    int RulesWithAlerts,
    Analysis? Analysis,
    List<SeverityCount> SeverityCounts,
    List<RuleAlertSummary> TopRules,
    List<RepositoryAlertSummary> TopRepositories,
    List<FilePathAlertSummary> TopFilePaths);
