//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRVA.Reports.WebAssembly.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScreenText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScreenText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRVA.Reports.WebAssembly.Properties.ScreenText", typeof(ScreenText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        internal static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts by Rule.
        /// </summary>
        internal static string AlertsByRule {
            get {
                return ResourceManager.GetString("AlertsByRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts by Severity.
        /// </summary>
        internal static string AlertsBySeverity {
            get {
                return ResourceManager.GetString("AlertsBySeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts by Tag.
        /// </summary>
        internal static string AlertsByTag {
            get {
                return ResourceManager.GetString("AlertsByTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string AnalysisDate {
            get {
                return ResourceManager.GetString("AnalysisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Details.
        /// </summary>
        internal static string AnalysisDetails {
            get {
                return ResourceManager.GetString("AnalysisDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        internal static string Context {
            get {
                return ResourceManager.GetString("Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Repo.
        /// </summary>
        internal static string ControllerRepo {
            get {
                return ResourceManager.GetString("ControllerRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Column.
        /// </summary>
        internal static string EndColumn {
            get {
                return ResourceManager.GetString("EndColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Line.
        /// </summary>
        internal static string EndLine {
            get {
                return ResourceManager.GetString("EndLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure Reason.
        /// </summary>
        internal static string FailureReason {
            get {
                return ResourceManager.GetString("FailureReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        internal static string Kind {
            get {
                return ResourceManager.GetString("Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CodeQL DB Repos.
        /// </summary>
        internal static string NoCodeQLDBRepos {
            get {
                return ResourceManager.GetString("NoCodeQLDBRepos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the content you are looking for does not exist..
        /// </summary>
        internal static string NotFoundMessage {
            get {
                return ResourceManager.GetString("NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found Repos.
        /// </summary>
        internal static string NotFoundRepos {
            get {
                return ResourceManager.GetString("NotFoundRepos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Limit Repos.
        /// </summary>
        internal static string OverLimitRepos {
            get {
                return ResourceManager.GetString("OverLimitRepos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Tags.
        /// </summary>
        internal static string PropertyTags {
            get {
                return ResourceManager.GetString("PropertyTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Language.
        /// </summary>
        internal static string QueryLanguage {
            get {
                return ResourceManager.GetString("QueryLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        internal static string Repositories {
            get {
                return ResourceManager.GetString("Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        internal static string Repository {
            get {
                return ResourceManager.GetString("Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository Alert Coverage.
        /// </summary>
        internal static string RepositoryAlertCoverage {
            get {
                return ResourceManager.GetString("RepositoryAlertCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository Breakdown.
        /// </summary>
        internal static string RepositoryBreakdown {
            get {
                return ResourceManager.GetString("RepositoryBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Fingerprint.
        /// </summary>
        internal static string ResultFingerprint {
            get {
                return ResourceManager.GetString("ResultFingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        internal static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Alert Coverage.
        /// </summary>
        internal static string RuleAlertCoverage {
            get {
                return ResourceManager.GetString("RuleAlertCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned Repos.
        /// </summary>
        internal static string ScannedRepos {
            get {
                return ResourceManager.GetString("ScannedRepos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string Severity {
            get {
                return ResourceManager.GetString("Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing top 10 results only.
        /// </summary>
        internal static string ShowingTop10 {
            get {
                return ResourceManager.GetString("ShowingTop10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sink.
        /// </summary>
        internal static string Sink {
            get {
                return ResourceManager.GetString("Sink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped Repos.
        /// </summary>
        internal static string SkippedRepos {
            get {
                return ResourceManager.GetString("SkippedRepos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet.
        /// </summary>
        internal static string Snippet {
            get {
                return ResourceManager.GetString("Snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Column.
        /// </summary>
        internal static string StartColumn {
            get {
                return ResourceManager.GetString("StartColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Line.
        /// </summary>
        internal static string StartLine {
            get {
                return ResourceManager.GetString("StartLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Count.
        /// </summary>
        internal static string StepCount {
            get {
                return ResourceManager.GetString("StepCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Repository Variant Analysis.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        internal static string ToolName {
            get {
                return ResourceManager.GetString("ToolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Version.
        /// </summary>
        internal static string ToolVersion {
            get {
                return ResourceManager.GetString("ToolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 25 Affected Repositories.
        /// </summary>
        internal static string Top10AffectedRepositories {
            get {
                return ResourceManager.GetString("Top10AffectedRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 25 Most Common File Paths.
        /// </summary>
        internal static string Top10CommonFilePaths {
            get {
                return ResourceManager.GetString("Top10CommonFilePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Alerts.
        /// </summary>
        internal static string TotalAlerts {
            get {
                return ResourceManager.GetString("TotalAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Repos.
        /// </summary>
        internal static string TotalRepos {
            get {
                return ResourceManager.GetString("TotalRepos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Repositories.
        /// </summary>
        internal static string TotalRepositories {
            get {
                return ResourceManager.GetString("TotalRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rules.
        /// </summary>
        internal static string TotalRules {
            get {
                return ResourceManager.GetString("TotalRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Runs.
        /// </summary>
        internal static string TotalRuns {
            get {
                return ResourceManager.GetString("TotalRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Alerts.
        /// </summary>
        internal static string WithAlerts {
            get {
                return ResourceManager.GetString("WithAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Alerts.
        /// </summary>
        internal static string WithoutAlerts {
            get {
                return ResourceManager.GetString("WithoutAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Run ID.
        /// </summary>
        internal static string WorkflowRunId {
            get {
                return ResourceManager.GetString("WorkflowRunId", resourceCulture);
            }
        }
    }
}
